version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: caixadesugestoes
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
